branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/  # version tags

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

install: skip

script:
  - cargo build --release --all
  - cargo test --release --all
  - cargo bench --no-run
